name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  buildTest:
    name: Build & Test JDK ${{ matrix.java_version }}
    runs-on: self-hosted
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.4.10
      - name: Debug keystore
        run: keytool -genkey -v -keystore app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
      - name: Build project
        run: ./gradlew assembleDebug
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: hannesa2/action-android/emulator-run-cmd@0.1.4.10
        with:
          cmd: ./gradlew cAT --continue
          api: 33
          tag: google_apis
          abi: arm64-v8a
          cmdOptions: -noaudio -no-boot-anim -no-window
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      - name: Archive Espresso results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Edgedetection-Espresso-report
          path: app/build/reports/androidTests/connected
      - name: Archive screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Edgedetection-Screenshots
          path: |
            app/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
            app/build/outputs/androidTest-results/connected
  Check:
    name: Check
    runs-on: self-hosted
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.4.10
      - name: Code checks
        run: ./gradlew lint
      - name: Archive Lint report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Edgedetection-Lint-report
          path: app/build/reports/lint-results*.html
